Last login: Thu Oct  8 20:49:59 on ttys000
/bin/bash -- '/Users/test/Desktop/Apo'\''s 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS'/start.sh
PCG-OSX-TEST:~ test$ /bin/bash -- '/Users/test/Desktop/Apo'\''s 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS'/start.sh
Traceback (most recent call last):
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/bin/bayesdb-demo", line 22, in <module>
    from bdbcontrib.demo import main
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/bdbcontrib/__init__.py", line 23, in <module>
    from bql_utils import cardinality
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/bdbcontrib/bql_utils.py", line 17, in <module>
    import pandas as pd
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/__init__.py", line 45, in <module>
    from pandas.core.api import *
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/core/groupby.py", line 15, in <module>
    from pandas.core.frame import DataFrame
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/core/frame.py", line 40, in <module>
    from pandas.core.series import Series
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/core/series.py", line 2737, in <module>
    import pandas.tools.plotting as _gfx
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/tools/plotting.py", line 28, in <module>
    import pandas.tseries.converter as conv
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in <module>
    rcParams = rc_params()
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 947, in rc_params
    fname = matplotlib_fname()
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 789, in matplotlib_fname
    path = get_data_path()  # guaranteed to exist or raise
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 325, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 693, in _get_data_path_cached
    defaultParams['datapath'][0] = _get_data_path()
  File "/Users/test/Desktop/Apo's 1" trõphe/Bayeslite-bayes0.1-23-g72682eb-bdbco0.1-1-g5b51594.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/__init__.py", line 661, in _get_data_path
    path = os.sep.join([os.path.dirname(__file__), 'mpl-data'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 32: ordinal not in range(128)
